/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpArrowUp: typeof import('~icons/ep/arrow-up')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpHide: typeof import('~icons/ep/hide')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMic: typeof import('~icons/ep/mic')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpPostcard: typeof import('~icons/ep/postcard')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    IEpVideoPlay: typeof import('~icons/ep/video-play')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
